
# note that the -lz option is necessary to link the zlib library 
codeEx4: codeExample4.cpp
	g++ -Wall -Wextra codeExample4.cpp -o codeEx4 -lz

codeEx5: codeExample5.cpp
	g++ -Wall -Wextra codeExample5.cpp -o codeEx5

